### PR TITLE
Rename Sync Pipelines to Solgate

### PR DESCRIPTION
**Pull request by tumido**
## Related Issues and Dependencies

#2

## This introduces a breaking change

- [x] Yes
- [ ] No

## This Pull Request implements

Rename the project to `solgate` and make it buildable and publishable.

### CODE REVIEW

**Comment by tumido** [comment]
@aicoe-aiops/sourceops can you help me please? Why is sesheta complaining here? Why does it use python 3.6 when [.thoth.yaml](https://github.com/aicoe-aiops/sync-pipelines/blob/master/.thoth.yaml) define 3.8 as a runtime environment? What settings file does effect sesheta's runtime? `pre-commit` passes just fine locally.

**Comment by tumido** [comment]
I have the same issue at #6

**Comment by 4n4nd** [comment]
:tada:

**Pull request merged**
