### PR TITLE
Make solgate fully Argo-CD deployable via Kustomize

### PR DESCRIPTION
**Pull request by tumido**
## Related Issues and Dependencies

--

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Will require changes to Argo CD - to include kustomize secret generator plugin, so it can build our secrets.

Deploys a Dev env only. Prod templates will follow

### CODE REVIEW

**Review by durandom — APPROVED** [review]
I dont have the 🧠 to review this. Please ask @HumairAK if you really need some 2nd 👀 to look at it, otherwise: LGTM :)

**Comment by tumido** [comment]
There will be some changes to this anyways, once we have the actual AI-CoE-CI's image builds, it's also not yet deployed anywhere, so I think it's good to merge it and fix afterwards. :)

All the templates are in a good shape and deployable - only the image can't be pulled since it's not imported. So.. all except the workflow content works.

**Pull request merged**
