### PR TITLE
Use PV for data exchange and fetch argo server role on the fly

### PR DESCRIPTION
**Pull request by tumido**
**Do not merge**

## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Use PV for intermediate storage - exchange of data between steps, and query for the Argo Server route dynamically, during the onExit handler execution.

### CODE REVIEW

**Review by martinpovolny — APPROVED** [review]
I understand these changes only partially.

**Comment by tumido** [comment]
@martinpovolny I'll try to provide a better explanation then :wink: :

### PersistentVolume storage

This section in `sensor.yaml` claims a PV named `workdir`

```yaml
volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 1Gi
```

This `workdir` can be mounted in individual steps as:

```yaml
volumeMounts:
  - name: workdir
    mountPath: /mnt/vol
```

### Rename command

Then this PR also changes the commands called during each step, since it changed in the CLI from the manifest draft used before - the data sending command: `s/transfer/send/`

### Failure handler
Since we're deplolying this via Kustomize instead of Ansible now, we don't have any easy way to inject the `ARGO_UI_HOST` route into the `notify` env vars. We need to query for it during the execution, that's what the `get-host` step is for:

```yaml
- name: get-host
  outputs:
    parameters:
      - name: host
        valueFrom:
          jsonPath: "{.spec.host}"
  resource:
    action: get
    manifest: |
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: argo-server
```
It looks up a `argo-server` route and stores its `.spec.host` property as an output parameter. This parameter is then used by the next step in `failure-handler` - the `notify` step as an argument (so it can be propagated to the env variable within that `notify` step):

```yaml
- name: failure-handler
  steps:
    - - name: get-host
        template: get-host
    - - name: notify
        template: notify
        arguments:
          parameters:
            - name: argo-ui-host
              value: "{{steps.get-host.outputs.parameters.host}}"
```

Querying for a `route` resource introduced a need to grant permissions to list/get `route`s for the default SA in the namespace. (Since this SA is used to execute the pod with). Instead of defining a new `Role`+`RoleBinding` I'm cutting corners here a bit and just grant `view` permissions to the SA instead, which seems safe enough to me.

**Comment by martinpovolny** [comment]
Thank you for the detailed explanation!

**Pull request merged**
